# Configuration for GitHub Labeler Action

# Add 'docs' label to any PR that changes a .md file
docs:
    - "**/*.md"

# Add 'release' label to any PR that is opened against the `production` branch
release:
    - base-branch: "production"

# Add 'feature' label to any PR with 'feature' in the PR title
feature:
    - title: ".*feature.*"
