services:
    uptime-monitor:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: Uptime_Monitor_Dev
        restart: always
        volumes:
            - ./:/app
            - /app/node_module
            - /app/.next
            - uptime_data:/data
        ports:
            - "3000:3000"
volumes:
    uptime_data:
