version: "3"
services:
    website:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - db
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: myRootPass
            MYSQL_DATABASE: uptimeDatabase
            MYSQL_USER: uptimeUser
            MYSQL_PASSWORD: uptimePass
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
