services:
    uptime_dev_db:
        image: mysql:latest
        container_name: uptime_db_dev
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: myRootPass
            MYSQL_DATABASE: uptimeDatabase
            MYSQL_USER: uptimeUser
            MYSQL_PASSWORD: uptimePass
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
