version: "3"
services:
    uptime_db:
        image: mysql:latest
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: myRootPass
            MYSQL_DATABASE: uptimeDatabase
            MYSQL_USER: uptimeUser
            MYSQL_PASSWORD: uptimePass
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
    uptime_client:
        image: beenhamo/uptime-monitor:latest
        restart: on-failure
        environment:
            DB_NAME: uptimeDatabase
            DB_USER: uptimeUser
            DB_PASS: uptimePass
        ports:
            - "3000:3000"
        depends_on:
            - uptime_db
        command: /bin/sh -c "npm run docker-prepare && npm start"
volumes:
    db_data:
