services:
    uptime-monitor:
        build:
            context: .
            target: dev
            dockerfile: Dockerfile.dev
        container_name: Uptime_Monitor_Dev
        restart: always
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
            - uptime_data:/data
        ports:
            - "3000:3000"
volumes:
    uptime_data:
