title: Uptime Monitor Docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://elbeenmachine.github.io/uptime-monitor/

aux_links:
    Template Repository: https://github.com/just-the-docs/just-the-docs-template
