name: Publish Development Docker Image

on:
    push:
        branches: ["staging"]

jobs:
    Publish-Docker-Image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: |
                  docker build -t beenhamo/uptime-monitor:beta .
                  docker tag beenhamo/uptime-monitor:beta

            - name: Push Docker images
              run: |
                  docker push beenhamo/uptime-monitor:beta
