name: Build Docker Image

on:
    pull_request:
        branches: ["production", "staging", "development"]

jobs:
    Publish-Docker-Image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build the Docker image
              run: docker build . --file Dockerfile
